### ISSUE TITLE
Where to put module.something

### ISSUE THREAD

**Issue by artoale** [vojtajina/node-di#1]
Hi! First of all, thank you! That some good news for angular fans :)

Now, a little question: where do you think is better to put module.value, module.factory, etc...?

I mean, the 'angular' way is to use the `angular.module('modulename').something` style directly when you define your components, but, as long as a global angular object is not available, this can't work (as it would require to pass a Module instance all over the place)

What do you think is the best 'use case' for this node DI implementation?

**Comment by artoale** [comment]
By looking at testacular integration with di, another question turned out: is the injector itself automatically injected (if required)?

**Comment by vojtajina** [comment]
Hi @artoale, I need to put together some readme, that will explain couple of things
- motivation for DI in general
- differences from the AngularJS implementation (and why these changes)
- examples how to use it

There is no global module register, you pass it by reference, that's correct. Look into testacular:

``` javascript
// some code that eventually wants to provide "plus" function
var plus = function() {
  // ....
};

// this is another notation of a module definition (that is plain JS and therefore does not require you to import the DI)
module.exports = {
  'plus': ['value', plus]
};
```

I think this is a common pattern, your node's module basically defines a DI module and in your bootstrap code you do something like:

``` javascript
var injector = new di.Injector([require('plus-module'), require('other-module')]);

injector.invoke(function(plus) {
  // kick your app
});
```

**Comment by vojtajina** [comment]
``` javascript
// equivalent to the module definition above, but nicer syntax
// I started with this, but now I'm more leaning towards the syntax above as it is plain JS
// and therefore does not require everybody to depend on the DI module
var m = module.exports = new di.Module();
m.value('x', plus);
```
