### ISSUE TITLE
Make interface identical to angular's

### ISSUE THREAD

**Issue by ashaffer** [vojtajina/node-di#2]
I'd like to be able to use the node di framework to share modules between client and server.  I currently have a hacked together version of this (ripped some code out of angular until it ran in node), but it'd be nice to have a less hacky library for this to use.

**Comment by vojtajina** [comment]
``` js
var nodeModule = new di.Module();
var angularModule = angular.module('x', []);

nodeModule.value == angularModule.value
nodeModule.factory == angularModule.factory
nodeModule.type == angularModule.service
```

If this is what you are asking, just create the `service` alias and you are good.

There are however other differences, eg. node-di does not have config phase and therefore there are no providers. This is not likely to change, I did this change on purpose.
